In [1]:
# impoeting needed Libraries 
import numpy as np
import pandas as pd
import plotly.express as px

In [2]:
## Display Max Columns in Pandas
pd.set_option('display.max_columns', None)

In [3]:
# loading the dataset
df=pd.read_csv('heart_disease.csv')
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,Yes,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,Yes,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,Yes,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,No,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,No,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,No,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9996,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,No,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9997,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,Yes,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9998,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,No,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9999,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,Yes,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

## Understanding Dataset
#Dataset Description
| Column Name             | Description | Brief Explanation |
|-------------------------|-------------|-------------------|
| Age | The individual's age. | Age affects overall heart disease risk. |
| Gender | The individual's gender (Male or Female). | Risk can vary between males and females. |
| Blood Pressure | The individual's blood pressure (systolic). | Higher systolic pressure increases risk. |
| Cholesterol Level | The individual's total cholesterol level. | High cholesterol contributes to plaque buildup. |
| Exercise Habits | The individual's exercise habits (Low, Medium, High). | More exercise generally reduces risk. |
| Smoking | Whether the individual smokes or not (Yes or No). | Smoking is a major heart disease risk factor. |
| Family Heart Disease | Family history of heart disease (Yes or No). | Genetics can increase risk. |
| Diabetes | Whether the individual has diabetes (Yes or No). | Diabetes significantly raises heart risk. |
| BMI | The individual's body mass index. | Higher BMI may indicate obesity-related risk. |
| High Blood Pressure | Whether the individual has high blood pressure (Yes or No). | Hypertension strains the heart. |
| Low HDL Cholesterol | Whether HDL is low (Yes or No). | Low “good cholesterol” raises risk. |
| High LDL Cholesterol | Whether LDL is high (Yes or No). | High “bad cholesterol” leads to plaque buildup. |
| Alcohol Consumption | Level of alcohol intake (None, Low, Medium, High). | Excessive alcohol increases risk. |
| Stress Level | The individual's stress level (Low, Medium, High). | High stress may negatively affect the heart. |
| Sleep Hours | Number of hours the individual sleeps. | Too little sleep is linked to higher risk. |
| Sugar Consumption | Sugar intake level (Low, Medium, High). | High sugar intake harms heart health. |
| Triglyceride Level | The individual's triglyceride level. | High triglycerides raise heart disease risk. |
| Fasting Blood Sugar | Blood sugar after fasting. | Elevated levels indicate diabetes or prediabetes. |
| CRP Level | C-reactive protein level, a marker of inflammation. | High CRP signals inflammation linked to heart issues. |
| Homocysteine Level | Homocysteine level, affecting blood vessel health. | High levels may damage blood vessels. |
| Heart Disease Status (Target) | Whether the individual has heart disease (Yes or No). | Target variable indicating heart disease presence. |

## Data Exploration

In [4]:
#Chec kData Types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   object
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   object
 5   Smoking               9975 non-null   object
 6   Family Heart Disease  9979 non-null   object
 7   Diabetes              9970 non-null   object
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   object
 10  Low HDL Cholesterol   9975 non-null   object
 11  High LDL Cholesterol  9974 non-null   object
 12  Alcohol Consumption   7414 non-null   object
 13  Stress Level          9978 non-null   object
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   object
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  object
dtypes: float64(9), object(12)
memory usage: 1.6+ MB

In [5]:
#Check duplicates
df.duplicated().sum()

np.int64(0)

In [6]:
#Check Missing Values
df.isna().mean().round(4).sort_values(ascending=False) *100

Alcohol Consumption     25.86
Diabetes                 0.30
Sugar Consumption        0.30
Cholesterol Level        0.30
Age                      0.29
Triglyceride Level       0.26
CRP Level                0.26
High LDL Cholesterol     0.26
High Blood Pressure      0.26
Low HDL Cholesterol      0.25
Sleep Hours              0.25
Exercise Habits          0.25
Smoking                  0.25
Fasting Blood Sugar      0.22
BMI                      0.22
Stress Level             0.22
Family Heart Disease     0.21
Homocysteine Level       0.20
Blood Pressure           0.19
Gender                   0.19
Heart Disease Status     0.00
dtype: float64

In [7]:
# Get missing value percentages
missing_values = df.isna().mean().round(4).sort_values(ascending=False) *100

# Get columns with >0% and <5% missing
missing_value_columns = missing_values[(missing_values > 0) & (missing_values <= 5)].index.tolist()
missing_value_columns

['Diabetes',
 'Sugar Consumption',
 'Cholesterol Level',
 'Age',
 'Triglyceride Level',
 'CRP Level',
 'High LDL Cholesterol',
 'High Blood Pressure',
 'Low HDL Cholesterol',
 'Sleep Hours',
 'Exercise Habits',
 'Smoking',
 'Fasting Blood Sugar',
 'BMI',
 'Stress Level',
 'Family Heart Disease',
 'Homocysteine Level',
 'Blood Pressure',
 'Gender']

In [8]:
#Check Numeric Columns 
df.describe().round()

,Age,Blood Pressure,Cholesterol Level,BMI,Sleep Hours,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level
count,9971.0,9981.0,9970.0,9978.0,9975.0,9974.0,9978.0,9974.0,9980.0
mean,49.0,150.0,225.0,29.0,7.0,251.0,120.0,7.0,12.0
std,18.0,18.0,44.0,6.0,2.0,87.0,24.0,4.0,4.0
min,18.0,120.0,150.0,18.0,4.0,100.0,80.0,0.0,5.0
25%,34.0,134.0,187.0,24.0,5.0,176.0,99.0,4.0,9.0
50%,49.0,150.0,226.0,29.0,7.0,250.0,120.0,7.0,12.0
75%,65.0,165.0,263.0,35.0,9.0,326.0,141.0,11.0,16.0
max,80.0,180.0,300.0,40.0,10.0,400.0,160.0,15.0,20.0

In [9]:
#Check Object Columns
df.describe(include='object')

,Gender,Exercise Habits,Smoking,Family Heart Disease,Diabetes,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sugar Consumption,Heart Disease Status
count,9981,9975,9975,9979,9970,9974,9975,9974,7414,9978,9970,10000
unique,2,3,2,2,2,2,2,2,3,3,3,2
top,Male,High,Yes,No,No,Yes,Yes,No,Medium,Medium,Low,No
freq,5003,3372,5123,5004,5018,5022,5000,5036,2500,3387,3390,8000

In [10]:
#In depth Checking form numirical Columns
num_cols=df.select_dtypes(include='number').columns
num_cols
for col in num_cols:
    px.histogram(data_frame=df,x=col,title=col).show()
    px.box(data_frame=df,x=col).show()

In [11]:
### In depth check for categorical columns
cat_cols = df.select_dtypes(include= 'object').columns

for col in cat_cols:

    print(col)
    print(df[col].nunique())
    print(df[col].unique())
    print('*' * 100)

Gender
2
['Male' 'Female' nan]
****************************************************************************************************
Exercise Habits
3
['High' 'Low' 'Medium' nan]
****************************************************************************************************
Smoking
2
['Yes' 'No' nan]
****************************************************************************************************
Family Heart Disease
2
['Yes' 'No' nan]
****************************************************************************************************
Diabetes
2
['No' 'Yes' nan]
****************************************************************************************************
High Blood Pressure
2
['Yes' 'No' nan]
****************************************************************************************************
Low HDL Cholesterol
2
['Yes' 'No' nan]
****************************************************************************************************
High LDL Cholesterol
2
['No' 'Yes' nan]
****************************************************************************************************
Alcohol Consumption
3
['High' 'Medium' 'Low' nan]
****************************************************************************************************
Stress Level
3
['Medium' 'High' 'Low' nan]
****************************************************************************************************
Sugar Consumption
3
['Medium' 'Low' 'High' nan]
****************************************************************************************************
Heart Disease Status
2
['No' 'Yes']
****************************************************************************************************

In [12]:
#Check Data Percentage after Dropping All Missing Values except Alcohol Consumption
(df.drop(columns='Alcohol Consumption').dropna().shape[0] / df.drop(columns='Alcohol Consumption').shape[0])*100

95.32000000000001

In [13]:
#Dropping Missing Values
df=df.dropna(subset=missing_value_columns,ignore_index=True)
df

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,Yes,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
1,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,Yes,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
2,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,No,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
3,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,No,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
4,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,No,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9527,25.0,Female,136.0,243.0,Medium,Yes,No,No,18.788791,Yes,No,Yes,Medium,High,6.834954,Medium,343.0,133.0,3.588814,19.132004,Yes
9528,38.0,Male,172.0,154.0,Medium,No,No,No,31.856801,Yes,No,Yes,NaN,High,8.247784,Low,377.0,83.0,2.658267,9.715709,Yes
9529,73.0,Male,152.0,201.0,High,Yes,No,Yes,26.899911,No,Yes,Yes,NaN,Low,4.436762,Low,248.0,88.0,4.408867,9.492429,Yes
9530,23.0,Male,142.0,299.0,Low,Yes,No,Yes,34.964026,Yes,No,Yes,Medium,High,8.526329,Medium,113.0,153.0,7.215634,11.873486,Yes
9531,38.0,Female,128.0,193.0,Medium,Yes,Yes,Yes,25.111295,No,Yes,Yes,High,Medium,5.659394,High,121.0,149.0,14.387810,6.208531,Yes

In [14]:
df.isna().sum()

Age                        0
Gender                     0
Blood Pressure             0
Cholesterol Level          0
Exercise Habits            0
Smoking                    0
Family Heart Disease       0
Diabetes                   0
BMI                        0
High Blood Pressure        0
Low HDL Cholesterol        0
High LDL Cholesterol       0
Alcohol Consumption     2465
Stress Level               0
Sleep Hours                0
Sugar Consumption          0
Triglyceride Level         0
Fasting Blood Sugar        0
CRP Level                  0
Homocysteine Level         0
Heart Disease Status       0
dtype: int64

### Data Preprocessing For Machine Learning

## 1 - Split Datafram into input & output

In [15]:
x=df.drop('Heart Disease Status',axis=1) # drop target column
y=df['Heart Disease Status'] #==> target Column

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [17]:
y

array([0, 0, 0, ..., 1, 1, 1])

# 2 -  Categorical Pipeline

In [18]:
cat_column=x.select_dtypes(include='object').columns
cat_column

Index(['Gender', 'Exercise Habits', 'Smoking', 'Family Heart Disease',
       'Diabetes', 'High Blood Pressure', 'Low HDL Cholesterol',
       'High LDL Cholesterol', 'Alcohol Consumption', 'Stress Level',
       'Sugar Consumption'],
      dtype='object')

In [123]:
from imblearn.pipeline import Pipeline
#from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer

#OHE = OneHotEncoder(drop='first',sparse_output=False)
ORD = OrdinalEncoder()
simp_imputer = SimpleImputer(strategy= 'constant', fill_value= 'never')

# cat_pipeline = Pipeline(steps= [ ('Imputer',simp_imputer),
#                                  ('OHE Encoder', OHE) ])
# cat_pipeline

cat_pipeline = Pipeline(steps= [ ('Imputer',simp_imputer),
                                 ('ORD Encoder', ORD) ])
cat_pipeline

Pipeline(steps=[('Imputer',
                 SimpleImputer(fill_value='never', strategy='constant')),
                ('ORD Encoder', OrdinalEncoder())])

# 3 -  Numerical Pipelines

In [124]:

num_cols = x.select_dtypes(include= 'number').columns

num_cols

Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')

In [125]:
# Data is Normally Destributed So No need To Use Robut Scaler
from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()

num_pipeline = Pipeline(steps= [ ('Scaling', min_max_scaler) ])
num_pipeline

Pipeline(steps=[('Scaling', MinMaxScaler())])

# 4 - Assign each column to its correponding Pipeline

In [126]:
from sklearn.compose import ColumnTransformer

preprocessing = ColumnTransformer(transformers= [ ('Num Pipeline', num_pipeline, num_cols),
                                                  ('Cat Pipeline', cat_pipeline, cat_column) ],
                                                  remainder= 'passthrough')
preprocessing

ColumnTransformer(remainder='passthrough',
                  transformers=[('Num Pipeline',
                                 Pipeline(steps=[('Scaling', MinMaxScaler())]),
                                 Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')),
                                ('Cat Pipeline',
                                 Pipeline(steps=[('Imputer',
                                                  SimpleImputer(fill_value='never',
                                                                strategy='constant')),
                                                 ('ORD Encoder',
                                                  OrdinalEncoder())]),
                                 Index(['Gender', 'Exercise Habits', 'Smoking', 'Family Heart Disease',
       'Diabetes', 'High Blood Pressure', 'Low HDL Cholesterol',
       'High LDL Cholesterol', 'Alcohol Consumption', 'Stress Level',
       'Sugar Consumption'],
      dtype='object'))])

# 5- Feature Engineering

In [127]:
from sklearn.preprocessing import FunctionTransformer


# feature engineering
def add_features(x):
    x = x.copy()
    x['hdl_ldl_risk'] = (
        (x['Low HDL Cholesterol'] == 'Yes') &
        (x['High LDL Cholesterol'] == 'Yes')
    ).astype(int)
    return x

feature_eng = FunctionTransformer(add_features)
feature_eng

FunctionTransformer(func=<function add_features at 0x0000029D874F95A0>)

# 6 -  Select Best Model

In [128]:
df['Heart Disease Status'].value_counts()

Heart Disease Status
No     7621
Yes    1911
Name: count, dtype: int64

In [129]:
num_neg = df['Heart Disease Status'].value_counts()[0]
num_pos = df['Heart Disease Status'].value_counts()[1]

xgb_pos_weight = num_neg / num_pos
xgb_pos_weight

C:\Users\Apex\AppData\Local\Temp\ipykernel_15824\3107884995.py:1: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

C:\Users\Apex\AppData\Local\Temp\ipykernel_15824\3107884995.py:2: FutureWarning:

Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`

np.float64(3.987964416535845)

In [130]:
num_neg

np.int64(7621)

# Handeling Imbalance WITH SMOTE

In [131]:
from imblearn.pipeline import Pipeline
from sklearn.model_selection import cross_validate

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from imblearn.over_sampling import SMOTE
models = [
    #('Logistic Regression', LogisticRegression(random_state= 42, n_jobs= -1)),
    ('KNN', KNeighborsClassifier(n_neighbors=17)),
    #('Naive Bayes', GaussianNB()),
    #('SVM Linear', SVC(random_state= 42, kernel= 'linear')),
    #('SVM rbf', SVC(random_state= 42, kernel= 'rbf')),
    #('Decision Tree', DecisionTreeClassifier(random_state= 42)),
    ('Random Forest', RandomForestClassifier(random_state= 42, n_jobs= -1)),
    ('XGBoost', XGBClassifier(random_state= 42, n_jobs= -1)),
    ('CatBoost', CatBoostClassifier(random_state= 42, verbose= 0)),
    #('LightGBM', LGBMClassifier(random_state= 42, n_jobs= -1, verbose = -1))
]



for model in models:

    model_pipeline = Pipeline(steps= [ ('Feature Engineering',feature_eng),('Preprocessing', preprocessing),('SMOTE',SMOTE(random_state=42)), ('Model', model[1]) ])
    cv_results = cross_validate(estimator= model_pipeline, X= x, y= y, cv= 5, scoring= ['accuracy', 'f1', 'precision', 'recall'], return_train_score= True)

    print(model[0])
    print('Accuracy :')
    print('Train accuracy :', round(cv_results['train_accuracy'].mean() * 100, 4))
    print('Test accuracy :', round(cv_results['test_accuracy'].mean() * 100, 4), '\n')

    print('F1 :')
    print('Train f1 :', round(cv_results['train_f1'].mean() * 100, 4))
    print('Test f1 :', round(cv_results['test_f1'].mean() * 100, 4), '\n')

    print('Precision :')
    print('Train precision :', round(cv_results['train_precision'].mean() * 100, 4))
    print('Test precision :', round(cv_results['test_precision'].mean() * 100, 4), '\n')

    print('Recall :')
    print('Train recall :', round(cv_results['train_recall'].mean() * 100, 4))
    print('Test recall :', round(cv_results['test_recall'].mean() * 100, 4), '\n')
    print('-' * 50)

KNN
Accuracy :
Train accuracy : 53.0948
Test accuracy : 43.3592

F1 :
Train f1 : 42.1567
Test f1 : 30.0098

Precision :
Train precision : 28.0016
Test precision : 19.9502

Recall :
Train recall : 85.2564
Test recall : 60.5447

--------------------------------------------------
Random Forest
Accuracy :
Train accuracy : 100.0
Test accuracy : 75.5455

F1 :
Train f1 : 100.0
Test f1 : 11.171

Precision :
Train precision : 100.0
Test precision : 20.5324

Recall :
Train recall : 100.0
Test recall : 7.6916

--------------------------------------------------
XGBoost
Accuracy :
Train accuracy : 96.9629
Test accuracy : 76.6891

F1 :
Train f1 : 91.8269
Test f1 : 7.9559

Precision :
Train precision : 99.664
Test precision : 19.2519

Recall :
Train recall : 85.1388
Test recall : 5.0236

--------------------------------------------------
CatBoost
Accuracy :
Train accuracy : 85.1369
Test accuracy : 79.8468

F1 :
Train f1 : 41.1284
Test f1 : 0.7222

Precision :
Train precision : 99.8037
Test precision : 26.3333

Recall :
Train recall : 25.9159
Test recall : 0.3662

--------------------------------------------------

# Handeling Imbalance Class Weight

In [132]:
from imblearn.pipeline import Pipeline
from sklearn.model_selection import cross_validate

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from imblearn.over_sampling import SMOTE



models = [ #('Logistic Regression' , LogisticRegression(random_state= 42, n_jobs= -1, class_weight= 'balanced')),
           #('Knn', KNeighborsClassifier(n_neighbors=17,n_jobs=-1)),
          # ('Gaussian NB', GaussianNB()),
          # ('SVC Linear', SVC(kernel= 'linear', random_state= 42)),
          # ('SVC RBF', SVC(kernel= 'rbf', random_state= 42)),
           ('Random Forest', RandomForestClassifier(random_state= 42, n_jobs = -1, class_weight={0:1, 1:3})),
           ('XGBoost', XGBClassifier(random_state= 42, n_jobs = -1, scale_pos_weight = xgb_pos_weight)),
           #('LGBM', LGBMClassifier(random_state= 42, n_jobs = -1, class_weight= 'balanced')),
           ('CatBoost', CatBoostClassifier(random_seed = 42, auto_class_weights= 'Balanced',verbose= 0))
         ]


for model in models:

    model_pipeline = Pipeline(steps= [ ('Feature Engineering',feature_eng),('Preprocessing', preprocessing), ('Model', model[1]) ])
    cv_results = cross_validate(estimator= model_pipeline, X= x, y= y, cv= 5, scoring= ['accuracy', 'f1', 'precision', 'recall'], return_train_score= True)

    print(model[0])
    print('Accuracy :')
    print('Train accuracy :', round(cv_results['train_accuracy'].mean() * 100, 4))
    print('Test accuracy :', round(cv_results['test_accuracy'].mean() * 100, 4), '\n')

    print('F1 :')
    print('Train f1 :', round(cv_results['train_f1'].mean() * 100, 4))
    print('Test f1 :', round(cv_results['test_f1'].mean() * 100, 4), '\n')

    print('Precision :')
    print('Train precision :', round(cv_results['train_precision'].mean() * 100, 4))
    print('Test precision :', round(cv_results['test_precision'].mean() * 100, 4), '\n')

    print('Recall :')
    print('Train recall :', round(cv_results['train_recall'].mean() * 100, 4))
    print('Test recall :', round(cv_results['test_recall'].mean() * 100, 4), '\n')
    print('-' * 50)

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

Random Forest
Accuracy :
Train accuracy : 100.0
Test accuracy : 79.9517

F1 :
Train f1 : 100.0
Test f1 : 0.0

Precision :
Train precision : 100.0
Test precision : 0.0

Recall :
Train recall : 100.0
Test recall : 0.0

--------------------------------------------------
XGBoost
Accuracy :
Train accuracy : 98.8486
Test accuracy : 70.2895

F1 :
Train f1 : 97.2085
Test f1 : 15.7533

Precision :
Train precision : 94.6173
Test precision : 18.266

Recall :
Train recall : 99.9477
Test recall : 13.8679

--------------------------------------------------
CatBoost
Accuracy :
Train accuracy : 94.1932
Test accuracy : 68.7894

F1 :
Train f1 : 87.0887
Test f1 : 19.8558

Precision :
Train precision : 78.5904
Test precision : 20.4793

Recall :
Train recall : 97.6583
Test recall : 19.3086

--------------------------------------------------

In [133]:
y

array([0, 0, 0, ..., 1, 1, 1])

# With Threshold

In [134]:
from imblearn.pipeline import Pipeline
from sklearn.model_selection import cross_validate

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import cross_validate, cross_val_predict
from sklearn.metrics import precision_score, recall_score ,f1_score



models = [ #('Logistic Regression' , LogisticRegression(random_state= 42, n_jobs= -1, class_weight= 'balanced')),
           #('Knn', KNeighborsClassifier(n_neighbors=17,n_jobs=-1)),
          # ('Gaussian NB', GaussianNB()),
          # ('SVC Linear', SVC(kernel= 'linear', random_state= 42)),
          # ('SVC RBF', SVC(kernel= 'rbf', random_state= 42)),
           ('Random Forest', RandomForestClassifier(random_state= 42, n_jobs = -1, class_weight= 'balanced')),
           ('XGBoost', XGBClassifier(random_state= 42, n_jobs = -1, scale_pos_weight = xgb_pos_weight)),
           #('LGBM', LGBMClassifier(random_state= 42, n_jobs = -1, class_weight= 'balanced')),
           ('CatBoost', CatBoostClassifier(random_seed = 42, scale_pos_weight = xgb_pos_weight,verbose= 0))
         ]
#,class_weights='balanced',auto_class_weights= 'Balanced'

for model in models:

    model_pipeline = Pipeline(steps= [ ('Feature Engineering',feature_eng),('Preprocessing', preprocessing), ('Model', model[1]) ])
   # cv_results = cross_validate(estimator= model_pipeline, X= x, y= y, cv= 5, scoring= ['accuracy', 'f1', 'precision', 'recall'], return_train_score= True)


    y_predict_proba = cross_val_predict(estimator= model_pipeline, X=x, y=y, cv= 5, method= 'predict_proba', n_jobs= -1)[:, 1]

    thresholds = [0.3, 0.2, 0.1, 0.05]

    print(model[0])

    for t in thresholds:

        print('Threshold :', t)

        y_pred = np.int64(y_predict_proba >= t)

        # Recall Score
        print('Test Recall :', round(recall_score(y, y_pred) * 100, 3))

        # Precision Score
        print('Test Precision :', round(precision_score(y, y_pred) * 100, 3))

        # F1 Score
        print('Test F1 :', round(f1_score(y, y_pred) * 100, 3), '\n')

    print('-' * 50)

Random Forest
Threshold : 0.3
Test Recall : 3.872
Test Precision : 20.219
Test F1 : 6.5

Threshold : 0.2
Test Recall : 52.015
Test Precision : 20.975
Test F1 : 29.895

Threshold : 0.1
Test Recall : 98.325
Test Precision : 20.064
Test F1 : 33.327

Threshold : 0.05
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

--------------------------------------------------
XGBoost
Threshold : 0.3
Test Recall : 39.613
Test Precision : 20.181
Test F1 : 26.74

Threshold : 0.2
Test Recall : 58.085
Test Precision : 20.174
Test F1 : 29.947

Threshold : 0.1
Test Recall : 79.801
Test Precision : 20.177
Test F1 : 32.21

Threshold : 0.05
Test Recall : 91.313
Test Precision : 20.122
Test F1 : 32.977

--------------------------------------------------
CatBoost
Threshold : 0.3
Test Recall : 80.167
Test Precision : 20.291
Test F1 : 32.386

Threshold : 0.2
Test Recall : 94.872
Test Precision : 20.223
Test F1 : 33.339

Threshold : 0.1
Test Recall : 99.581
Test Precision : 20.101
Test F1 : 33.451

Threshold : 0.05
Test Recall : 99.948
Test Precision : 20.055
Test F1 : 33.406

--------------------------------------------------

# With Params + SMOTE

In [135]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import precision_score, recall_score, f1_score

models = [
    ('Random Forest', RandomForestClassifier(random_state=42, n_jobs=-1)),
    ('XGBoost', XGBClassifier(random_state=42, n_jobs=-1, eval_metric='logloss')),
    ('CatBoost', CatBoostClassifier(random_seed=42, verbose=0))

    # ('Random Forest', RandomForestClassifier(random_state= 42, n_jobs= -1)),
    # ('XGBoost', XGBClassifier(random_state= 42, n_jobs= -1)),
    # ('CatBoost', CatBoostClassifier(random_state= 42, verbose= 0))

]

param_grids = {
    'Random Forest': {
        'Model__n_estimators': [200, 400],
        'Model__max_depth': [None, 5, 10]#,
        #'Model__class_weight': ['balanced', {0:1, 1:3}]
    },
    'XGBoost': {
        'Model__n_estimators': [200, 400],
        'Model__max_depth': [3, 5],
        'Model__learning_rate': [0.01, 0.05],
        'Model__gamma': [0, 1]#,
       # 'Model__scale_pos_weight': [1, 3, 5]
    },
    'CatBoost': {
        'Model__iterations': [300, 500],
        'Model__depth': [4, 6],
        'Model__learning_rate': [0.01, 0.05]#,
       # 'Model__scale_pos_weight': [1, 3, 5]
    }
}

for model in models:

    print(model[0])

    pipeline = Pipeline(steps=[('FeatureEng', feature_eng),('Preprocess', preprocessing),('SMOTE', SMOTE(random_state=42)),('Model', model[1])])

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grids[model[0]],scoring={'f1': 'f1', 'recall': 'recall', 'precision': 'precision'},refit='recall',   cv=5,n_jobs=-1)

    grid.fit(x, y)
    best_model = grid.best_estimator_
    print("Best score:", grid.best_score_)
    print("Best Params:", grid.best_params_)

    # Probabilities
    y_proba = cross_val_predict(
        best_model, x, y,
        cv=5,
        method='predict_proba',
        n_jobs=-1
    )[:, 1]

Random Forest
Best score: 0.37414870203545997
Best Params: {'Model__max_depth': 5, 'Model__n_estimators': 400}
XGBoost
Best score: 0.3411917488004593
Best Params: {'Model__gamma': 0, 'Model__learning_rate': 0.01, 'Model__max_depth': 3, 'Model__n_estimators': 200}
CatBoost
Best score: 0.034527633863272865
Best Params: {'Model__depth': 4, 'Model__iterations': 300, 'Model__learning_rate': 0.01}

# With Params + Class Weigth

In [136]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import precision_score, recall_score, f1_score

models = [
    ('Random Forest', RandomForestClassifier(random_state=42, n_jobs=-1)),
    ('XGBoost', XGBClassifier(random_state=42, n_jobs=-1, scale_pos_weight=xgb_pos_weight, eval_metric='logloss')),
    ('CatBoost', CatBoostClassifier(random_seed=42, verbose=0, scale_pos_weight=xgb_pos_weight))

    # ('Random Forest', RandomForestClassifier(random_state= 42, n_jobs= -1)),
    # ('XGBoost', XGBClassifier(random_state= 42, n_jobs= -1)),
    # ('CatBoost', CatBoostClassifier(random_state= 42, verbose= 0))

]

param_grids = {
    'Random Forest': {
        'Model__n_estimators': [200, 400],
        'Model__max_depth': [None, 5, 10],
        'Model__class_weight': ['balanced', {0:1, 1:3}]
    },
    'XGBoost': {
        'Model__n_estimators': [200, 400],
        'Model__max_depth': [3, 5],
        'Model__learning_rate': [0.01, 0.05],
        'Model__gamma': [0, 1],
        'Model__scale_pos_weight': [1, 3, 5]
    },
    'CatBoost': {
        'Model__iterations': [300, 500],
        'Model__depth': [4, 6],
        'Model__learning_rate': [0.01, 0.05],
        'Model__scale_pos_weight': [1, 3, 5]
    }
}

for model in models:

    print(model[0])

    pipeline = Pipeline(steps=[('FeatureEng', feature_eng),('Preprocess', preprocessing),('Model', model[1])])

    grid = GridSearchCV(
        estimator=pipeline,
        param_grid=param_grids[model[0]],scoring={'f1': 'f1', 'recall': 'recall', 'precision': 'precision'},refit='recall',   cv=5,n_jobs=-1)

    grid.fit(x, y)
    best_model = grid.best_estimator_
    print("Best score:", grid.best_score_)
    print("Best Params:", grid.best_params_)

    # Probabilities
    y_proba = cross_val_predict(
        best_model, x, y,
        cv=5,
        method='predict_proba',
        n_jobs=-1
    )[:, 1]

Random Forest
Best score: 0.28937705904064087
Best Params: {'Model__class_weight': 'balanced', 'Model__max_depth': 5, 'Model__n_estimators': 200}
XGBoost
Best score: 0.9482044482112831
Best Params: {'Model__gamma': 0, 'Model__learning_rate': 0.01, 'Model__max_depth': 3, 'Model__n_estimators': 200, 'Model__scale_pos_weight': 5}
CatBoost

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:


9 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
9 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\imblearn\pipeline.py", line 522, in fit
    self._final_estimator.fit(Xt, yt, **last_step_params["fit"])
  File "c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\catboost\core.py", line 5245, in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
  File "c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\catboost\core.py", line 2410, in _fit
    self._train(
  File "c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\catboost\core.py", line 1790, in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5023, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5072, in _catboost._CatBoost._train
_catboost.CatBoostError: (Error 1224: The requested operation cannot be performed on a file with a user-mapped section open.) util/system/file.cpp:936: can't open "catboost_info\\catboost_training.json" with mode CreateAlways (0x00000004)


c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning:

One or more of the test scores are non-finite: [0.         0.         0.33369107 0.         0.09836269 0.31455083
 0.         0.00309278 0.33200924 0.         0.13703559 0.30068611
 0.         0.00723301 0.32887831 0.         0.10929046 0.28485684
 0.         0.02296588        nan        nan        nan        nan]

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning:

One or more of the test scores are non-finite: [0.         0.         0.99267699 0.         0.06331114 0.7064536
 0.         0.00157068 0.95657594 0.         0.10099381 0.5860949
 0.         0.00366082 0.90738999 0.         0.07535166 0.47514114
 0.         0.01203368        nan        nan        nan        nan]

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning:

One or more of the test scores are non-finite: [0.         0.         0.20055589 0.         0.224663   0.20234063
 0.         0.1        0.20086994 0.         0.21504774 0.20223205
 0.         0.44166667 0.20084517 0.         0.200679   0.20341219
 0.         0.27487395        nan        nan        nan        nan]

Best score: 0.9926769920577418
Best Params: {'Model__depth': 4, 'Model__iterations': 300, 'Model__learning_rate': 0.01, 'Model__scale_pos_weight': 5}

# Params With Threshold

In [137]:
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV, cross_val_predict
from sklearn.metrics import precision_score, recall_score, f1_score


models = [
    ('Random Forest', RandomForestClassifier(random_state=42, n_jobs=-1)),
    ('XGBoost', XGBClassifier(random_state=42, n_jobs=-1, scale_pos_weight=xgb_pos_weight, eval_metric='logloss')),
    ('CatBoost', CatBoostClassifier(random_seed=42, verbose=0, scale_pos_weight=xgb_pos_weight))

]

param_grids = {
    'Random Forest': {
        'Model__n_estimators': [200, 400],
        'Model__max_depth': [None, 5, 10],
        'Model__class_weight': ['balanced', {0:1, 1:3}]
    },
    'XGBoost': {
        'Model__n_estimators': [200, 400],
        'Model__max_depth': [3, 5],
        'Model__learning_rate': [0.01, 0.05],
        'Model__gamma': [0, 1]#,
       # 'Model__scale_pos_weight': [1, 3, 5]
    },
    'CatBoost': {
        'Model__iterations': [300, 500],
        'Model__depth': [4, 6],
        'Model__learning_rate': [0.01, 0.05]#,
       # 'Model__scale_pos_weight': [1, 3, 5]
    }
}

for model in models:

    print(model[0])

    pipeline = Pipeline(steps=[
        ('FeatureEng', feature_eng),
        ('Preprocess', preprocessing),
        #('SMOTE', SMOTE(random_state=42)),
        ('Model', model[1])
    ])

    grid = GridSearchCV(estimator=pipeline,param_grid=param_grids[model[0]],scoring={'f1': 'f1', 'recall': 'recall', 'precision': 'precision'},refit='recall',cv=5,n_jobs=-1)

    grid.fit(x, y)
    best_model = grid.best_estimator_
    #print("Best Model:", grid.best_estimator_)
    print("Best score:", grid.best_score_)
    print("Best Params:", grid.best_params_)


    # Probabilities
    y_predict_proba = cross_val_predict(estimator= best_model, X=x, y=y, cv= 5, method= 'predict_proba', n_jobs= -1)[:, 1]

    #thresholds = [0.3, 0.2, 0.1, 0.05]
    thresholds = [0.9, 0.7, 0.5,0.3, 0.2, 0.1, 0.05]

    #print(model[0])

    for t in thresholds:

        print('Threshold :', t)

        y_pred = np.int64(y_predict_proba >= t)

        # Recall Score
        print('Test Recall :', round(recall_score(y, y_pred) * 100, 3))

        # Precision Score
        print('Test Precision :', round(precision_score(y, y_pred) * 100, 3))

        # F1 Score
        print('Test F1 :', round(f1_score(y, y_pred) * 100, 3), '\n')

    print('-' * 50)

Random Forest
Best score: 0.28937705904064087
Best Params: {'Model__class_weight': 'balanced', 'Model__max_depth': 5, 'Model__n_estimators': 200}
Threshold : 0.9
Test Recall : 0.0
Test Precision : 0.0
Test F1 : 0.0

Threshold : 0.7
Test Recall : 0.0
Test Precision : 0.0
Test F1 : 0.0

Threshold : 0.5
Test Recall : 28.938
Test Precision : 20.558
Test F1 : 24.038

Threshold : 0.3
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

Threshold : 0.2
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

Threshold : 0.1
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

Threshold : 0.05
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

--------------------------------------------------
XGBoost

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

Best score: 0.4767145571610187
Best Params: {'Model__gamma': 0, 'Model__learning_rate': 0.01, 'Model__max_depth': 3, 'Model__n_estimators': 200}
Threshold : 0.9
Test Recall : 0.0
Test Precision : 0.0
Test F1 : 0.0

Threshold : 0.7
Test Recall : 0.0
Test Precision : 0.0
Test F1 : 0.0

Threshold : 0.5
Test Recall : 47.671
Test Precision : 19.869
Test F1 : 28.048

Threshold : 0.3
Test Recall : 99.948
Test Precision : 20.048
Test F1 : 33.397

Threshold : 0.2
Test Recall : 100.0
Test Precision : 20.05
Test F1 : 33.403

Threshold : 0.1
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

Threshold : 0.05
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

--------------------------------------------------
CatBoost

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

Best score: 0.4086900058780912
Best Params: {'Model__depth': 4, 'Model__iterations': 300, 'Model__learning_rate': 0.01}
Threshold : 0.9
Test Recall : 0.0
Test Precision : 0.0
Test F1 : 0.0

Threshold : 0.7
Test Recall : 0.0
Test Precision : 0.0
Test F1 : 0.0

Threshold : 0.5
Test Recall : 40.869
Test Precision : 20.461
Test F1 : 27.27

Threshold : 0.3
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

Threshold : 0.2
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

Threshold : 0.1
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

Threshold : 0.05
Test Recall : 100.0
Test Precision : 20.048
Test F1 : 33.4

--------------------------------------------------

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

c:\Users\Apex\anaconda3\envs\Apex\lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.

In [138]:
XGBoost_pipeline = Pipeline(steps= [ ('Preprocessing', preprocessing), ('Model', XGBClassifier(random_state=42, n_jobs=-1, scale_pos_weight=xgb_pos_weight,gamma=0, learning_rate=0.01, max_depth=3, n_estimators=200 ,eval_metric='logloss')) ])

XGBoost_pipeline.fit(x, y)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Scaling',
                                                                   MinMaxScaler())]),
                                                  Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')),
                                                 ('Cat Pipeline',
                                                  Pipeline(steps=[('Imputer',
                                                                   Sim...
                               feature_types=None, feature_weights=None,
                               gamma=0, grow_policy=None, importance_type=None,
                               interaction_constraints=None, learning_rate=0.01,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=3, max_leaves=None,
                               min_child_weight=None, missing=nan,
                               monotone_constraints=None, multi_strategy=None,
                               n_estimators=200, n_jobs=-1,
                               num_parallel_tree=None, ...))])

In [139]:
sample=x.sample()
print(XGBoost_pipeline.predict(sample)[0],XGBoost_pipeline.predict_proba(sample)[0])

# y_proba = XGBoost_pipeline.predict_proba(sample)[:, 1]

# y_pred = (y_proba >= 0.3).astype(int)

# print(y_pred,y_proba)

0 [0.50790626 0.49209374]

In [140]:
CATBoost_pipeline_model = Pipeline(steps= [ ('Preprocessing', preprocessing), ('Model', CatBoostClassifier(random_state=42, depth=4, iterations=300, learning_rate=0.01,scale_pos_weight=xgb_pos_weight,verbose=0 )) ])

CATBoost_pipeline_model.fit(x, y)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Scaling',
                                                                   MinMaxScaler())]),
                                                  Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')),
                                                 ('Cat Pipeline',
                                                  Pipeline(steps=[('Imputer',
                                                                   Sim...='never',
                                                                                 strategy='constant')),
                                                                  ('ORD '
                                                                   'Encoder',
                                                                   OrdinalEncoder())]),
                                                  Index(['Gender', 'Exercise Habits', 'Smoking', 'Family Heart Disease',
       'Diabetes', 'High Blood Pressure', 'Low HDL Cholesterol',
       'High LDL Cholesterol', 'Alcohol Consumption', 'Stress Level',
       'Sugar Consumption'],
      dtype='object'))])),
                ('Model',
                 <catboost.core.CatBoostClassifier object at 0x0000029D87D95CC0>)])

In [141]:
sample=x.sample()
print(CATBoost_pipeline_model.predict(sample)[0],CATBoost_pipeline_model.predict_proba(sample).round(3)[0][1]*100)

0 49.4

In [142]:
CATBoost_pipeline_model.named_steps['Model']

In [143]:
deployment_model_pipeline = Pipeline(steps= [ ('Preprocessing', preprocessing), ('Model', CatBoostClassifier(random_state=42, depth=4, iterations=300, learning_rate=0.01,scale_pos_weight=xgb_pos_weight,verbose=0 )) ])

deployment_model_pipeline.fit(x, y)

Pipeline(steps=[('Preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('Num Pipeline',
                                                  Pipeline(steps=[('Scaling',
                                                                   MinMaxScaler())]),
                                                  Index(['Age', 'Blood Pressure', 'Cholesterol Level', 'BMI', 'Sleep Hours',
       'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level',
       'Homocysteine Level'],
      dtype='object')),
                                                 ('Cat Pipeline',
                                                  Pipeline(steps=[('Imputer',
                                                                   Sim...='never',
                                                                                 strategy='constant')),
                                                                  ('ORD '
                                                                   'Encoder',
                                                                   OrdinalEncoder())]),
                                                  Index(['Gender', 'Exercise Habits', 'Smoking', 'Family Heart Disease',
       'Diabetes', 'High Blood Pressure', 'Low HDL Cholesterol',
       'High LDL Cholesterol', 'Alcohol Consumption', 'Stress Level',
       'Sugar Consumption'],
      dtype='object'))])),
                ('Model',
                 <catboost.core.CatBoostClassifier object at 0x0000029D87D97F40>)])

In [144]:
features=deployment_model_pipeline[0].get_feature_names_out()
features

array(['Num Pipeline__Age', 'Num Pipeline__Blood Pressure',
       'Num Pipeline__Cholesterol Level', 'Num Pipeline__BMI',
       'Num Pipeline__Sleep Hours', 'Num Pipeline__Triglyceride Level',
       'Num Pipeline__Fasting Blood Sugar', 'Num Pipeline__CRP Level',
       'Num Pipeline__Homocysteine Level', 'Cat Pipeline__Gender',
       'Cat Pipeline__Exercise Habits', 'Cat Pipeline__Smoking',
       'Cat Pipeline__Family Heart Disease', 'Cat Pipeline__Diabetes',
       'Cat Pipeline__High Blood Pressure',
       'Cat Pipeline__Low HDL Cholesterol',
       'Cat Pipeline__High LDL Cholesterol',
       'Cat Pipeline__Alcohol Consumption', 'Cat Pipeline__Stress Level',
       'Cat Pipeline__Sugar Consumption'], dtype=object)

In [145]:
Importances=deployment_model_pipeline[1].feature_importances_
Importances

array([10.89948769,  8.06902344,  5.40162919,  9.50813997,  5.75859083,
        6.52668107,  7.70078795,  6.5071508 ,  7.89543482,  2.03588435,
        5.26583536,  0.60938849,  0.71133861,  1.4386492 ,  0.49472141,
        0.60551117,  0.73360642,  5.13647055,  8.76970597,  5.93196271])

In [146]:
importance_df=pd.DataFrame({'Feature': features ,'Importance': Importances})
importance_df=importance_df.sort_values(by='Importance',ascending= False,ignore_index=True)
importance_df

                               Feature  Importance
0                    Num Pipeline__Age   10.899488
1                    Num Pipeline__BMI    9.508140
2           Cat Pipeline__Stress Level    8.769706
3         Num Pipeline__Blood Pressure    8.069023
4     Num Pipeline__Homocysteine Level    7.895435
5    Num Pipeline__Fasting Blood Sugar    7.700788
6     Num Pipeline__Triglyceride Level    6.526681
7              Num Pipeline__CRP Level    6.507151
8      Cat Pipeline__Sugar Consumption    5.931963
9            Num Pipeline__Sleep Hours    5.758591
10     Num Pipeline__Cholesterol Level    5.401629
11       Cat Pipeline__Exercise Habits    5.265835
12   Cat Pipeline__Alcohol Consumption    5.136471
13                Cat Pipeline__Gender    2.035884
14              Cat Pipeline__Diabetes    1.438649
15  Cat Pipeline__High LDL Cholesterol    0.733606
16  Cat Pipeline__Family Heart Disease    0.711339
17               Cat Pipeline__Smoking    0.609388
18   Cat Pipeline__Low HDL Cholesterol    0.605511
19   Cat Pipeline__High Blood Pressure    0.494721

# Deployment

In [147]:
##     Dase Dataset
df.to_csv('Cleaned_ML_df.csv')
importance_df.to_csv('importance.csv')

In [148]:
# Save Model
import joblib

joblib.dump(deployment_model_pipeline,'Catboost_Model.pkl')

['Catboost_Model.pkl']

In [149]:
import streamlit as st

In [159]:
%%writefile Heart_Disease_prediction_deployment.py

import streamlit as st
import pandas as pd
import plotly.express as px
import joblib

from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import GridSearchCV, cross_val_predict ,cross_validate
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import LabelEncoder,OneHotEncoder,MinMaxScaler,FunctionTransformer
from sklearn.impute import SimpleImputer

from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier



html_title = """<h1 style="color:white;text-align:center;"> <span style="color:red">Heart Disease </span> Risk Exploratory Data Analysis & Prediction</h1>"""
st.markdown(html_title, unsafe_allow_html=True)
    # Set Title 
st.set_page_config(layout='wide', page_title= 'Heart Disease Risk EDA & HD Prediction',page_icon='💔')

page = st.sidebar.radio('Page', ['Home','Dash Board', 'Statistics', 'Dynamic Reports','Heart Disease Prediction'])

#@st.cache_data
#def load_data():
df = pd.read_csv('cleaned_df.csv', index_col= 0)
ML_df = pd.read_csv('cleaned_ML_df.csv', index_col= 0)
importance_df=pd.read_csv('importance.csv',index_col=0)
 #return df

#try:
#    df=load_data()

if page == 'Home':



    # Insert Image
    col1, col2, col3 = st.columns([1,2,1])

    
    col2.image(width=1000,image='https://www.riversidehealthcare.org/sites/default/files/healthcurrents/GettyImages-1344030014.jpg')


    st.header('Dataset Overview')
    col1, col2 = st.columns([2,1])

    col1.dataframe(df,height=1100)

        # Create table of column descriptions
    data = {
        "Column Name": [
            "Gender", "Age", "Age_Segment", "Blood Pressure",
            "Blood_Pressure_Ranges", "High Blood Pressure", "Stress Level",
            "Cholesterol Level", "Low HDL Cholesterol", "High LDL Cholesterol","Exercise Habits","Smoking","Diabetes","Sugar Consumption",
            "Fasting Blood Sugar", "BMI", "BMI categories", "Alcohol Consumption",
            "Sleep Hours", "Sleep_Type", "Triglyceride Level", "trigly_level",
            "CRP Level", "CRP_Group", "Homocysteine Level",
            "Homocysteine_Category", "Family Heart Disease",
            "Heart Disease Status", "Heart Disease Binary"
        ],
        "Description": [
            "Biological sex of the individual",
            "Age in years",
            "Categorized age segment",
            "Systolic blood pressure (mm/Hg)",
            "Blood pressure classification",
            "Whether the person has high BP",
            "Self-reported stress level",
            "Total cholesterol (mg/dL)",
            "Indicates low HDL cholesterol",
            "Indicates High HDL cholesterol",
            "Exercise habits (Low, Medium, High)",
            "Smoker or not (Yes or No)",
            "Diabetes or not (Yes or No)",
            "Daily sugar intake level",
            "Fasting blood glucose level",
            "Body Mass Index",
            "BMI classification",
            "Alcohol consumption level",
            "Average daily sleep duration",
            "Sleep quality category",
            "Triglyceride level (mg/dL)",
            "Triglyceride range classification",
            "C-Reactive Protein level",
            "CRP classification",
            "Homocysteine level",
            "Homocysteine category",
            "Family history of heart disease",
            "Heart disease type/status",
            "Binary heart disease indicator"
        ]
    }

    desc_df = pd.DataFrame(data)

    # Display table
    col2.subheader("📝 Column Descriptions")
    col2.table(desc_df)

elif page == 'Statistics':

    #col1, col2 = st.columns([1,1])

    #with col1:
    cat_col = [
        'Heart Disease Status','Gender','Age_Segment','Blood_Pressure_Ranges',
        'Stress Level','Low HDL Cholesterol','High LDL Cholesterol',
        'Exercise Habits','Smoking','Diabetes','Sugar Consumption','BMI categories',
        'Alcohol Consumption','Sleep_Type','trigly_level','CRP_Group',
        'Homocysteine_Category','Family Heart Disease'
    ]

    st.title("Categorical Analysis for Heart Disease")

    for col in cat_col:
        result = df[df['Heart Disease Status'] == 'Yes'].groupby(col)['Per'].sum().round(2).reset_index().sort_values('Per', ascending=False)
        
        with st.expander(f"📊 {col}"):
            col1, col2 = st.columns([1,1])

            #st.dataframe(result)
            col1.dataframe(result)
            Chart_Type=col1.radio('Chart Type :',options=['Histrogram','Pie'],key=col)
            if Chart_Type=='Histrogram':

                col2.plotly_chart(px.histogram(result, x=col, y='Per',text_auto= True, title=f"{col}"))
            else :
                col2.plotly_chart(px.pie(result, names=col, values='Per', title=f"{col}"))


elif page == 'Dash Board':

    cat_col = [
        'Heart Disease Status','Gender','Age_Segment','Blood_Pressure_Ranges',
        'Stress Level','Low HDL Cholesterol','High LDL Cholesterol',
        'Exercise Habits','Smoking','Diabetes','Sugar Consumption','BMI categories',
        'Alcohol Consumption','Sleep_Type','trigly_level','CRP_Group',
        'Homocysteine_Category','Family Heart Disease'
    ]

    st.title("Categorical Analysis for Heart Disease")

    for col in cat_col:
        result = df[df['Heart Disease Status'] == 'Yes'].groupby(col)['Per'].sum().round(2).reset_index().sort_values('Per', ascending=False)
        
        col1, col2 = st.columns([1,1])
        
        col2.dataframe(result)
        Chart_Type=col2.radio('Chart Type :',options=['Histrogram','Pie'],key=col)

        if Chart_Type=='Histrogram':
            col1.plotly_chart(px.histogram(result, x=col, y='Per',text_auto= True, title=f"{col}"))
        else :
            col1.plotly_chart(px.pie(result, names=col, values='Per', title=f"{col}"))

        
        co1,col2,col3 =st.columns([1,2,1])

        col2.write(f"### 💗 ▂▃▅▇ {col.upper()} ANALYSIS ▇▅▃▂ 💗")
        st.write("-----")


elif page =='Dynamic Reports' :

    col1, col2 = st.columns([3,1])

    All_gender =  ['Choose'] + df.Gender.unique().tolist() 
    Gender = st.sidebar.selectbox('Gender', All_gender)

    age_group=st.sidebar.selectbox('Age Group', ['All Age Groups','Teenager', 'Young Adult','Adult', 'Middle-Aged','Senior'])

    Boold_pressure_ranges =  ['All Ranges'] + ['Normal  [80-120]','Elevated  [120-129]','Stage 1 Hypertension  [130-139]','Stage 2 Hypertension [140 & above]'] 
    
    Boold_pressure_ranges = st.sidebar.selectbox('Blood Pressure Ranges', Boold_pressure_ranges)

    Alcohol_Consumption =  ['All'] +  ['Most likly Never','Low','Medium','High']
    
    Alcohol_Consumption = st.sidebar.selectbox('Alcohol Consumption', Alcohol_Consumption)

    BMI_categories =  ['All Categories'] + ['Underweight','Normal weight','Overweight','Obesity'] 
    
    BMI_categories = st.sidebar.selectbox('BMI categories', BMI_categories)

    CRP_Group =  ['All Groups'] + ['Normal/Low', 'Marked Elevation','Moderate Elevation']
    
    CRP_Group = st.sidebar.selectbox('CRP Group', CRP_Group)    
    
    Homocysteine_Category =  ['All Categories'] + ['Marked Elevation', 'Moderate Elevation','Severe Elevation'] 
    
    Homocysteine_Category = st.sidebar.selectbox('Homocysteine categories', Homocysteine_Category)

    Stress=st.sidebar.radio('Stess Level', options=['All'] + ['Low','Medium','High'],horizontal=True )

    Exercise_Habits=st.sidebar.radio('Exercise Habits', options=['All'] +  ['Low','Medium','High'],horizontal=True )

    Smoker=st.sidebar.radio('Smoker',options=['All','No','Yes'],horizontal=True)

    LDL_Cholesterol=st.sidebar.radio('Cholesterol',options=['All','No','Yes'],horizontal=True)

    Diabetes=st.sidebar.radio('Diabetes',options=['All','No','Yes'],horizontal=True)

    Family_Heart_Disease=st.sidebar.radio('Family Heart History',options=['All','No','Yes'],horizontal=True)

    Sleep=st.sidebar.radio('Sleep Type',options=['Any','Normal', 'Light', 'Deep'],horizontal=True)

    trigly_level = st.sidebar.radio('Triglyceride Level', ['All'] + ['Normal','High','Borderline'],horizontal=True)




    dF_select=col2.multiselect('Data Frame',df.drop(columns=['Per','Heart Disease Status','High Blood Pressure'],axis=1).columns,max_selections=26,default=df.drop(columns=['Per','Heart Disease Status','High Blood Pressure'],axis=1).columns)

    if dF_select != '':

        df_filtered_col = ['Heart Disease Status'] + dF_select

        df_filtered=df[df['Heart Disease Status']=='Yes'].groupby(df_filtered_col)['Per'].sum()
        df_filtered=df_filtered.reset_index().sort_values(by='Per',ascending=False)

    
    if Gender != 'Choose' and 'Gender' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Gender'] == Gender]

    if Smoker != 'All' and 'Smoking' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Smoking'] == Smoker]

    if age_group != 'All Age Groups' and 'Age_Segment' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Age_Segment'] == age_group]

    if Boold_pressure_ranges != 'All Ranges' and 'Blood_Pressure_Ranges' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Blood_Pressure_Ranges'] == Boold_pressure_ranges]


    if Alcohol_Consumption != 'All' and 'Alcohol Consumption' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Alcohol Consumption'] == Alcohol_Consumption]       


    if BMI_categories != 'All Categories' and 'BMI categories' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['BMI categories'] == BMI_categories]  

    if CRP_Group != 'All Groups' and 'CRP_Group' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['CRP_Group'] == CRP_Group]  

    if Homocysteine_Category != 'All Categories' and 'Homocysteine_Category' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Homocysteine_Category'] == Homocysteine_Category]  

    if Stress != 'All' and 'Stress Level' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Stress Level'] == Stress]  
 
    if Exercise_Habits != 'All' and 'Exercise Habits' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Exercise Habits'] == Exercise_Habits]     

    if Diabetes != 'All' and 'Diabetes' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Diabetes'] == Diabetes]  

    if Sleep != 'Any' and 'Sleep_Type' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Sleep_Type'] == Sleep]  

    if trigly_level != 'All' and 'trigly_level' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['trigly_level'] == trigly_level] 


    if Family_Heart_Disease != 'All' and 'Family Heart Disease' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['Family Heart Disease'] == Family_Heart_Disease] 

    if LDL_Cholesterol != 'All' and 'High LDL Cholesterol' in df_filtered_col:

        df_filtered = df_filtered[df_filtered['High LDL Cholesterol'] == LDL_Cholesterol] 


    if dF_select != '':
        col1.dataframe(df_filtered)
        st.plotly_chart(px.histogram(df_filtered, x=dF_select, y='Per',barmode='overlay',height=600,text_auto= True))
            
    else :
        col1.dataframe(df)

elif page =='Heart Disease Prediction' :

    colA ,colB = st.columns([3,1])

    col1, col2, col3 ,col4 = colA.columns([1,1,1,1])

    col111,col112 =colA.columns([6,1])

    col5, col6, col7 ,col8 = colA.columns([1,1,1,1])

    col113,col114 =colA.columns([6,1])

    col9, col10 ,col11,col12 = colA.columns([1,1,1,1])

    col115,col116 =colA.columns([6,1])

    col13, col14 ,col15 ,col16 = colA.columns([1,1,1,1])

    col117,col118 =colA.columns([6,1])

    col17, col18, col19 ,col20 = colA.columns([1,1,1,1])

    col119,col120 =colA.columns([6,1])

    Age_pre = col1.slider('Age',step=1)

    Gender_per = col2.radio('Gender', df.Gender.unique(),horizontal=True)

    Smoker_pre = col3.radio('Smoker',options=['No','Yes'],horizontal=True)

    Family_Heart_Disease_pre =col4.radio('Family Heart History',options=['No','Yes'],horizontal=True)

    col111.write("-----")


    Diabetes_pre =col5.radio('Diabetes',options=['No','Yes'],horizontal=True)

    Sugar_Consumption_pre = col6.radio('Sugar Consumption', options=['Low','Medium','High'],horizontal=True )

    Fasting_Blood_Sugar_pre = col7.number_input('Fasting Blood Sugar',min_value=40)

    BMI_pre = col8.number_input('BMI',min_value=15.000,max_value=35.000)

    col113.write("-----")

    Stress_pre =col9.radio('Stess Level', options=['Low','Medium','High'],horizontal=True )

    High_Blood_Pressure_pre =col10.radio('High Blood Pressure',options=['No','Yes'],horizontal=True)

    Blood_Pressure_pre = col11.number_input('Blood Pressure' )

    Sleep_Hours_pre = col12.number_input('Sleep Hours',min_value=1.000,max_value=23.000)



    col115.write("-----")


    Low_HDL_Cholesterol_pre = col13.radio('Low HDL Cholesterol',options=['No','Yes'],horizontal=True)
    
    High_LDL_Cholesterol_pre = col14.radio('High LDL Cholesterol',options=['No','Yes'],horizontal=True)

    Cholesterol_Level_pre = col15.number_input('Cholesterol Level',min_value=100.000)

    Alcohol_Consumption_pre = col16.selectbox('Alcohol Consumption', ['never','Low','Medium','High'])

    col117.write("-----")


    Exercise_Habits_pre =col17.radio('Exercise Habits', ['Low','Medium','High'],horizontal=True )

    Triglyceride_Level_pre = col18.number_input('Triglyceride Level',min_value=150.000,max_value=500.000)

    CRP_Level_pre = col19.number_input('CRP Level',min_value=0.1)

    Homocysteine_Level_pre = col20.number_input('Homocysteine Level',min_value=5.000)

    col119.write("-----")

    


    # Create Predicted row
    input_columns = ML_df.columns.drop('Heart Disease Status')
    predicted_data = pd.DataFrame(columns= input_columns, data= [[Age_pre,Gender_per, Blood_Pressure_pre, Cholesterol_Level_pre, Exercise_Habits_pre, Smoker_pre, Family_Heart_Disease_pre,
                                                                  Diabetes_pre,BMI_pre,High_Blood_Pressure_pre,Low_HDL_Cholesterol_pre, High_LDL_Cholesterol_pre,Alcohol_Consumption_pre, 
                                                                  Stress_pre, Sleep_Hours_pre,Sugar_Consumption_pre, Triglyceride_Level_pre, Fasting_Blood_Sugar_pre,CRP_Level_pre, 
                                                                  Homocysteine_Level_pre]])

    # Load Model


        
    model = joblib.load('Catboost_Model.pkl')

    result = model.predict(predicted_data)[0]

    button = colA.button('Predict HD Probability')

    if button == True:

        if result == 1:
            colA.error('HD Probabily Positive')
            colA.write(model.predict_proba(predicted_data).round(3)[0][1] *100)

        else:
            colA.success('HD Nigative')
            colA.write(model.predict_proba(predicted_data).round(3)[0][1] *100)


    # Display Important Features Table
    colB.subheader("📝 Important Features")
    colB.table(importance_df)

Overwriting Heart_Disease_prediction_deployment.py

In [160]:
! streamlit run Heart_Disease_prediction_deployment.py

^C

In [154]:
ML_df=pd.read_csv('cleaned_ML_df.csv',index_col=0)
ML_df.columns.drop('Heart Disease Status')

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level'],
      dtype='object')

In [155]:
import plotly.io as pio
# Reset to Default theme
pio.templates.default='plotly'

In [156]:
! pipreqs

INFO: Not scanning for jupyter notebooks.
WARNING: requirements.txt already exists, use --force to overwrite it

In [157]:
df.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='object')